### ISSUE TITLE
Thoughts on using kytv's i2p repo post-install

### ISSUE THREAD

**Issue by chris-barry** [TheTinHat/i2pbootstrap#1]
Hi,

Do you have any thoughts on using kytv's Debian repo that is hosted in the i2p network? This would be done after using the i2p2.no repo to get started. Personally, I always think it's a good idea to use in-network resources. I don't know if there would be an issue hopping between package providers.

**Comment by kytvi2p** [comment]
It should work fine, and the packages at http://deb.i2p2.no and http://killyourtv.i2p are identical. I build them, add them to my repository, then upload them to the 'official' repository. 

Friends have used my repository via I2P without issue. Something like the following should suffice for anyone interested in doing this:

```
echo 'Acquire::HTTP::Proxy::killyourtv.i2p "http://127.0.0.1:4444";' > /etc/apt/apt.conf.d/10_i2pproxy
echo 'deb http://killyourtv.i2p/debian wheezy main' > /etc/apt/sources.list/kytv.list
```

Perhaps at some point we can have an `apt-transport-i2p` package or I2P-support added to https://github.com/diocles/apt-transport-tor

**Comment by chris-barry** [comment]
Would that also work with http://deb.i2p2.no in `i2p.list`?

**Comment by kytvi2p** [comment]
> Would that also work with http://deb.i2p2.no in `i2p.list`?

Yes, both repositories can co-exist without conflict.
